import type { Metadata } from "next";
import { Anek_Latin } from "next/font/google";
import "./globals.css";
import Nav from "./components/template/Nav";

const geistSans = Anek_Latin({
  variable: "--font-anek-latin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PhotoUP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased w-screen flex flex-col items-center`}>
        <Nav/>  
        {children}
      </body>
    </html>
  );
}
