import type { Metadata } from "next";
import { Anek_Latin } from "next/font/google";
import "./globals.css";
import Nav from "./components/template/Nav";

import { ThemeProvider } from "@/components/Theme";
import { LanguageProvider } from "@/contexts/locale";

const geistSans = Anek_Latin({
  variable: "--font-anek-latin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PhotoUP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} antialiased w-screen flex flex-col items-center`}>
        <LanguageProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Nav/>  

            {children}
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
